### ISSUE TITLE
Add README for Sujiko challenge

### ISSUE THREAD

**Issue by critesjosh** [RareSkills/noir-puzzles#10]
Similar to https://github.com/RareSkills/noir-puzzles/issues/6, but for Sujiko

**Comment by critesjosh** [comment]
It looks like the forge tests for Sujko also only test the validity of the question. If both `forge test` and `nargo test` should be run, explain what each test is testing in the README,

**Comment by burke-md** [comment]
Will break out the README in a PR w/ Sudoku and clear up the testing as a seperate issue. Thanks for this note @critesjosh.
