### ISSUE TITLE
Update `constrain` to `assert()`

### ISSUE THREAD

**Issue by critesjosh** [RareSkills/noir-puzzles#5]
We are actually deprecating the constrain statement in favor of an assert function. See [this](https://noir-lang.org/language_concepts/constrain) warning. I see this when running tests on v 0.6.0.

![image](https://github.com/RareSkills/noir-puzzles/assets/18372439/65bfa713-73b1-48e2-b05b-982c7317da47)

This test passes without warnings.

```rust
#[test]
// Do not modify this function
fn test_add() {
  assert(main(4, 5) == 9);
  assert(main(2, 9) == 11);
}
```

**Comment by burke-md** [comment]
Thanks for the very clear explaination here. Will resolve this.
