### ISSUE TITLE
Add a README to the Sudoku challenge

### ISSUE THREAD

**Issue by critesjosh** [RareSkills/noir-puzzles#6]
Since the structure of this puzzle is a bit more complex, I think it would be helpful to put the instructions for completion into a README in `./Sudoku` rather than as comments in the circuit file.

Something like 
1. Finish the circuit to check for a valid solution.
2. Generate the solidity verifier contract with `nargo codegen-verifier`.
3. Generate proofs with `nargo prove p`
4. Check solution with `forge test` or `nargo test`, or both (?)

**Comment by burke-md** [comment]
README.md has been broken out. As tests are re-written, they and their work flow will be better documented there. 
Will contiue this aspect of the issue [here](https://github.com/RareSkills/noir-puzzles/issues/8). 

Thanks @critesjosh
