### ISSUE TITLE
Remove return type from function definition in Sudoku circuit

### ISSUE THREAD

**Issue by critesjosh** [RareSkills/noir-puzzles#7]
Regarding this code: https://github.com/RareSkills/noir-puzzles/blob/26979463c2dac45ea838322c312edf8517d3bb4d/circuits/Sudoku/circuits/src/main.nr#L77-L81

Can you just remove the return type? So the function signature would be 
```rust
fn main(question: pub [Field;16], answer :  [Field;16]) {}
```

Or does this still give you an error?

**Comment by burke-md** [comment]
This is a great point.
On one hand, removing the return type from the function signature does resolve the error. The error says main() is expecting a return of type Field but receives type ().  The first time I encountered this, I had a semi colon preventing the compiler from seeing the last expression as an implicit return. The docs/stackoverflow information was a little thin for troubleshooting this. So I was hoping to prevent friction for new users by including a temp return value.
This also allows TDD minded folk to see the test fail without a compiler error.

On the other hand, up until this point in the puzzles the user has not needed to edit the function signature of the main().

Perhaps a strong way forward would be editing the function signature as you have suggested @critesjosh and provide some very clear explanation in the README.md (that will be created, as suggested in another issue).

What do you think?

**Comment by critesjosh** [comment]
I think providing an explanation in the README as well as comments directly in the code makes sense, since comments are used as guide elsewhere in the file.

**Comment by burke-md** [comment]
This has been resolved in a PR.
The documentation will continue to improve as the tests are re-written. See [issue 8](https://github.com/RareSkills/noir-puzzles/issues/8).
