### ISSUE TITLE
Implement tests for correct answer in Sudoku

### ISSUE THREAD

**Issue by critesjosh** [RareSkills/noir-puzzles#8]
If I run `nargo test` and `forge test` without implementing a solution check in the circuit for the Sudoku puzzle, all of the test still pass.

I would expect at least some of the tests to fail if I haven't implement a solution yet.

**Comment by burke-md** [comment]
Similar to comment in [issue 10](https://github.com/RareSkills/noir-puzzles/issues/10)

Clarify testing intent and document.

**Comment by supernovahs** [comment]
Completed  in #25
